import type { Category } from "@/types/catalog";

export const categories: Category[] = [
  {
    slug: "apartments",
    index: "01",
    name: "Apartments",
    shortName: "Apartments",
    tagline: "Elevated urban living.",
    description: "Urban living, intelligently selected.",
    heroHeadline: "Elevated urban living.",
    heroSubline:
      "Premium residences in cities where location, build quality and long-term demand still hold.",
    audience: [
      "1–5 BHK apartments",
      "Premium residences",
      "Urban homes",
      "Investment apartments",
      "Ready-to-move and under-construction projects",
    ],
    cta: "Explore Apartments",
    accent: "gold",
    hero: {
      src: "/media/categories/apartments.svg",
      alt: "Abstract rendering of a contemporary apartment facade",
      placeholder: true,
      caption: null,
    },
  },
  {
    slug: "villas",
    index: "02",
    name: "Villas",
    shortName: "Villas",
    tagline: "Space. Privacy. Ownership.",
    description: "Private spaces designed for elevated living.",
    heroHeadline: "Space. Privacy. Ownership.",
    heroSubline:
      "Independent residences for buyers who want land, light and distance from the next front door.",
    audience: [
      "Luxury villas",
      "Second homes",
      "Holiday homes",
      "Gated communities",
      "Premium residences",
    ],
    cta: "Explore Villas",
    accent: "gold",
    hero: {
      src: "/media/categories/villas.svg",
      alt: "Abstract rendering of a low-rise villa and courtyard",
      placeholder: true,
      caption: null,
    },
  },
  {
    slug: "commercial",
    index: "03",
    name: "Commercial Spaces",
    shortName: "Commercial",
    tagline: "Real estate with an income thesis.",
    description: "Income-producing real estate opportunities.",
    heroHeadline: "Real estate with an income thesis.",
    heroSubline:
      "Retail, office and pre-leased assets evaluated on lease structure, tenant quality and yield.",
    audience: [
      "Retail",
      "Offices",
      "Commercial units",
      "Pre-leased assets",
      "Investment properties",
    ],
    cta: "Explore Commercial",
    accent: "steel",
    hero: {
      src: "/media/categories/commercial.svg",
      alt: "Abstract rendering of a commercial tower grid",
      placeholder: true,
      caption: null,
    },
  },
  {
    slug: "sustainable-living",
    index: "04",
    name: "Sustainable Living",
    shortName: "Sustainable",
    tagline: "Built around a better future.",
    description: "Homes designed around a better future.",
    heroHeadline: "Built around a better future.",
    heroSubline:
      "Communities planned around green architecture, water, energy and the land they sit on.",
    audience: [
      "Sustainable communities",
      "Eco-conscious villas",
      "Green architecture",
      "Nature-centric living",
      "Wellness-oriented communities",
    ],
    cta: "Discover Sustainable Living",
    accent: "sage",
    hero: {
      src: "/media/categories/sustainable-living.svg",
      alt: "Abstract rendering of a low-rise community set into a green landscape",
      placeholder: true,
      caption: null,
    },
  },
  {
    slug: "spiritual-residences",
    index: "05",
    name: "Spiritual Residences",
    shortName: "Spiritual",
    tagline: "Where living meets inner peace.",
    description:
      "Residences shaped by serenity, nature, wellness and proximity to places of spiritual significance.",
    heroHeadline: "Where living meets inner peace.",
    heroSubline:
      "Discover residences shaped by serenity, nature, wellness and proximity to places of spiritual significance.",
    audience: [
      "Spiritual destinations",
      "Pilgrimage locations",
      "Meditation communities",
      "Wellness residences",
      "Nature and spirituality",
      "Second homes near spiritual centres",
      "Retreat-oriented properties",
    ],
    cta: "Explore Spiritual Residences",
    accent: "lotus",
    hero: {
      src: "/media/categories/spiritual-residences.svg",
      alt: "Abstract rendering of a still water court framed by an open colonnade",
      placeholder: true,
      caption: null,
    },
  },
  {
    slug: "plots",
    index: "06",
    name: "Plots",
    shortName: "Plots",
    tagline: "Own the land. Shape what comes next.",
    description: "Own the land. Build the future.",
    heroHeadline: "Own the land. Shape what comes next.",
    heroSubline:
      "Plotted developments and land holdings for buyers working to a longer horizon.",
    audience: [
      "Residential plots",
      "Investment land",
      "Second-home plots",
      "Gated plotted developments",
      "Land banking",
    ],
    cta: "Explore Plots",
    accent: "sage",
    hero: {
      src: "/media/categories/plots.svg",
      alt: "Abstract rendering of a plotted development laid over open land",
      placeholder: true,
      caption: null,
    },
  },
];

export const categoryBySlug = new Map(categories.map((c) => [c.slug, c]));
