import type { Money, PlotUnit, Project } from "@/types/catalog";

const inr = (amount: number): Money => ({ amount, currency: "INR" });

const gallery = (slug: string, alts: string[]) =>
  alts.map((alt, i) => ({
    src: `/media/projects/${slug}/gallery-0${i + 1}.svg`,
    alt,
    placeholder: true,
    caption: null,
  }));

const samplePlots = (slug: string, rows: Array<[string, number, string, PlotUnit["status"], number, number]>): PlotUnit[] =>
  rows.map(([plotNumber, size, facing, status, x, y]) => ({
    kind: "plot",
    id: `${slug}-${plotNumber}`,
    plotNumber,
    area: { min: size, max: null, unit: "sqyd" },
    facing,
    roadWidthFt: null,
    status,
    price: null,
    sample: true,
    plan: { x, y, w: 9, h: 11 },
  }));

/**
 * Every factual value here traces to docs/prd/*.txt. Anything the brief does not
 * state is null and renders as "On request". Do not fill these in from memory —
 * see AGENTS.md and run `pnpm check:data`.
 */
export const projects: Project[] = [
  {
    slug: "omaxe-chowk",
    name: "Omaxe Chowk",
    positioning: "Own a piece of Delhi's next commercial destination.",
    summary:
      "A commercial real-estate opportunity in one of Delhi's historic commercial districts.",
    categories: ["commercial"],
    primaryCategory: "commercial",
    propertyTypes: ["commercial"],
    intents: ["rental-income", "buy-commercial"],
    purposes: ["investment", "rental-income", "commercial-income"],
    location: {
      label: "Chandni Chowk, Delhi",
      cities: ["Delhi"],
      region: "Chandni Chowk",
      state: "Delhi",
      coordinates: null,
    },
    priceFrom: inr(10000000),
    priceNote: "Indicative starting value. Final consideration is confirmed against the unit and payment structure.",
    area: null,
    bedrooms: [],
    availability: "available",
    specialTags: ["pre-leased", "high-rental-potential", "premium-location", "investment-opportunity"],
    usps: ["Pre-leased commercial opportunity", "Chandni Chowk trade district", "Lease-backed income thesis"],
    overview: [
      "Omaxe Chowk sits inside Chandni Chowk, one of Delhi's oldest and most continuously traded commercial districts.",
      "TokenZameen presents it as an income-oriented holding: the case rests on the lease structure and the catchment, not on speculative appreciation.",
    ],
    whyThisProject: [
      "A pre-leased structure, so the income position is documented rather than projected. The lease itself is shared on request.",
      "A trade catchment with decades of established footfall.",
      "Unit-level entry rather than whole-floor commitment.",
    ],
    highlights: [
      { label: "Property Type", value: "Commercial", icon: "type" },
      { label: "Location", value: "Chandni Chowk", icon: "location" },
      { label: "Status", value: "Pre-Leased", icon: "status" },
      { label: "Price", value: "₹1 Cr onwards", icon: "price" },
      { label: "Ownership", value: "100%", icon: "ownership" },
      { label: "Lease", value: "5 years, PDC (indicative)", icon: "lease" },
    ],
    amenities: [],
    connectivity: [],
    intelligence: null,
    commercial: {
      propertyValue: inr(10000000),
      initialInvestment: inr(5000000),
      monthlyRent: inr(75000),
      annualRent: inr(900000),
      grossYieldPercent: 9,
      leaseTenure: "5 years, post-dated cheques",
      ownership: "100%",
      paymentStructure: null,
      preLeased: true,
      tenant: null,
    },
    inventory: [
      { kind: "commercial", id: "omaxe-chowk-u1", unitNumber: "Unit 01", floor: null, area: null, monthlyRent: null, leaseStatus: null, tenant: null, status: "available", price: null, sample: true },
      { kind: "commercial", id: "omaxe-chowk-u2", unitNumber: "Unit 02", floor: null, area: null, monthlyRent: null, leaseStatus: null, tenant: null, status: "available", price: null, sample: true },
      { kind: "commercial", id: "omaxe-chowk-u3", unitNumber: "Unit 03", floor: null, area: null, monthlyRent: null, leaseStatus: null, tenant: null, status: "available", price: null, sample: true },
      { kind: "commercial", id: "omaxe-chowk-u4", unitNumber: "Unit 04", floor: null, area: null, monthlyRent: null, leaseStatus: null, tenant: null, status: "available", price: null, sample: true },
    ],
    masterplan: null,
    documents: [
      { id: "omaxe-chowk-brochure", title: "Project brochure", kind: "brochure", href: null, gated: false },
      { id: "omaxe-chowk-price-list", title: "Unit price list", kind: "price-list", href: null, gated: true },
      { id: "omaxe-chowk-lease", title: "Lease documentation", kind: "lease", href: null, gated: true },
      { id: "omaxe-chowk-payment-plan", title: "Payment structure", kind: "payment-plan", href: null, gated: true },
      { id: "omaxe-chowk-rera", title: "RERA details", kind: "rera", href: null, gated: false },
    ],
    faqs: [
      {
        question: "Is the rental income guaranteed?",
        answer:
          "No. The figures shown are indicative and derive from the lease structure presented for the asset. Actual income depends on the executed lease, the tenant's performance, applicable taxes and your own expenses.",
      },
      {
        question: "What does the pre-leased status mean for me as a buyer?",
        answer:
          "It means a lease arrangement is in place at the point of purchase, so the income position is evidenced by documentation rather than projected. Your advisor will walk you through the lease before any commitment.",
      },
      {
        question: "What is the minimum I need to commit?",
        answer:
          "The indicative structure is ₹50 lakh initial investment against a ₹1 crore property value. The exact structure is confirmed unit by unit.",
      },
    ],
    pendingInformation: [
      "Commercial unit types and sizes",
      "Floor-wise availability",
      "Tenant information, where legally shareable",
      "Payment structure",
      "RERA registration details",
    ],
    developer: { name: "Omaxe", about: null, established: null },
    reraNumber: null,
    possession: null,
    hero: {
      src: "/media/projects/omaxe-chowk/hero.svg",
      alt: "Placeholder artwork for Omaxe Chowk",
      placeholder: true,
      caption: null,
    },
    gallery: gallery("omaxe-chowk", [
      "Placeholder artwork for Omaxe Chowk, image 1 of 4",
      "Placeholder artwork for Omaxe Chowk, image 2 of 4",
      "Placeholder artwork for Omaxe Chowk, image 3 of 4",
      "Placeholder artwork for Omaxe Chowk, image 4 of 4",
    ]),
    verified: { project: false, developer: false, location: false, documentation: false, pricing: false, inventory: false },
    lastUpdated: "2026-09-20",
    featured: true,
    editorialRank: 100,
  },
  {
    slug: "luxofy",
    name: "Luxofy",
    positioning: "Luxury, curated for modern living.",
    summary: "A curated collection of luxury villas and apartments in Goa.",
    categories: ["villas", "apartments"],
    primaryCategory: "villas",
    propertyTypes: ["villa", "apartment"],
    intents: ["buy-a-home", "second-home"],
    purposes: ["self-use", "second-home", "investment"],
    location: { label: "Goa", cities: ["Goa"], region: null, state: "Goa", coordinates: null },
    priceFrom: null,
    priceNote: null,
    area: null,
    bedrooms: [],
    availability: "available",
    specialTags: ["premium-location"],
    usps: [
      "Premium residences",
      "Luxury architecture",
      "Lifestyle amenities",
      "Spacious layouts",
      "Location advantages",
    ],
    overview: [
      "Luxofy is TokenZameen's luxury residential collection in Goa, spanning both villas and apartments under one address.",
      "It is presented as a lifestyle holding first and an investment second — a home you would want to use, in a market with genuine second-home demand.",
    ],
    whyThisProject: [
      "One collection, two formats: take a villa for land and privacy, or an apartment for a lighter footprint.",
            "Architecture and amenity are the point, not an afterthought.",
    ],
    highlights: [
      { label: "Property Type", value: "Villas & Apartments", icon: "type" },
      { label: "Location", value: "Goa", icon: "location" },
      { label: "Availability", value: "Available", icon: "status" },
      { label: "Price", value: "On request", icon: "price" },
    ],
    amenities: [],
    connectivity: [],
    intelligence: null,
    commercial: null,
    inventory: [],
    masterplan: null,
    documents: [
      { id: "luxofy-brochure", title: "Collection brochure", kind: "brochure", href: null, gated: false },
      { id: "luxofy-floor-plans", title: "Floor plans", kind: "floor-plan", href: null, gated: true },
      { id: "luxofy-price-list", title: "Price list", kind: "price-list", href: null, gated: true },
      { id: "luxofy-rera", title: "RERA details", kind: "rera", href: null, gated: false },
    ],
    faqs: [
      {
        question: "Can I see both the villas and the apartments?",
        answer:
          "Yes. Luxofy is a single collection with two formats. Tell your advisor which way you are leaning and they will structure the site visit around it.",
      },
      {
        question: "Why is no price shown?",
        answer:
          "We publish a price only once the developer has released a rate we can stand behind. Request details and an advisor will share the current position in writing.",
      },
    ],
    pendingInformation: [
      "Unit configurations and carpet areas",
      "Starting price and payment plan",
      "Amenity schedule",
      "Possession timeline",
      "RERA registration details",
    ],
    developer: null,
    reraNumber: null,
    possession: null,
    hero: {
      src: "/media/projects/luxofy/hero.svg",
      alt: "Placeholder artwork for Luxofy",
      placeholder: true,
      caption: null,
    },
    gallery: gallery("luxofy", [
      "Placeholder artwork for Luxofy, image 1 of 4",
      "Placeholder artwork for Luxofy, image 2 of 4",
      "Placeholder artwork for Luxofy, image 3 of 4",
      "Placeholder artwork for Luxofy, image 4 of 4",
    ]),
    verified: { project: false, developer: false, location: false, documentation: false, pricing: false, inventory: false },
    lastUpdated: "2026-09-20",
    featured: true,
    editorialRank: 92,
  },
  {
    slug: "garden-court",
    name: "Garden Court",
    positioning: "Own the land. Create your vision.",
    summary: "Residential plots on the Goa–Maharashtra border, sized from 360 to 515 sq. yd.",
    categories: ["plots"],
    primaryCategory: "plots",
    propertyTypes: ["plot"],
    intents: ["own-land", "second-home"],
    purposes: ["land-banking", "capital-appreciation", "second-home"],
    location: {
      label: "Goa–Maharashtra Border",
      cities: ["Goa", "Maharashtra"],
      region: "Goa–Maharashtra border",
      state: null,
      coordinates: null,
    },
    priceFrom: null,
    priceNote: null,
    area: { min: 360, max: 515, unit: "sqyd" },
    bedrooms: [],
    availability: "available",
    specialTags: [],
    usps: ["Residential plots", "360–515 sq. yd.", "Goa–Maharashtra border location"],
    overview: [
      "Garden Court is a plotted residential development on the Goa–Maharashtra border, with plots running from 360 to 515 square yards.",
      "It suits a buyer who wants to hold land and build to their own brief rather than take a finished product.",
    ],
    whyThisProject: [
      "Plot sizes large enough for an independent home rather than a row house.",
      "A border location that reads to both the Goa and the Maharashtra market.",
      "Whether a construction timeline applies is confirmed from the development's terms before you commit.",
    ],
    highlights: [
      { label: "Property Type", value: "Residential plots", icon: "type" },
      { label: "Location", value: "Goa–Maharashtra border", icon: "location" },
      { label: "Plot Size", value: "360–515 sq. yd.", icon: "area" },
      { label: "Price", value: "On request", icon: "price" },
    ],
    amenities: [],
    connectivity: [],
    intelligence: null,
    commercial: null,
    inventory: samplePlots("garden-court", [
      ["P-01", 360, "East", "available", 8, 12],
      ["P-02", 400, "East", "sold", 20, 12],
      ["P-03", 420, "North", "available", 32, 12],
      ["P-04", 515, "North", "available", 44, 12],
      ["P-05", 360, "West", "reserved", 56, 12],
      ["P-06", 400, "West", "available", 68, 12],
      ["P-07", 450, "South", "available", 8, 40],
      ["P-08", 480, "South", "sold", 20, 40],
      ["P-09", 360, "East", "available", 32, 40],
      ["P-10", 515, "East", "available", 44, 40],
      ["P-11", 400, "North", "reserved", 56, 40],
      ["P-12", 420, "North", "available", 68, 40],
      ["P-13", 360, "West", "available", 8, 68],
      ["P-14", 450, "West", "available", 20, 68],
      ["P-15", 515, "South", "sold", 32, 68],
      ["P-16", 480, "South", "available", 44, 68],
      ["P-17", 400, "East", "available", 56, 68],
      ["P-18", 360, "East", "reserved", 68, 68],
    ]),
    masterplan: {
      src: "/media/projects/garden-court/masterplan.svg",
      alt: "Indicative plotted layout for Garden Court",
      placeholder: true,
      caption: "Indicative layout. Plot positions are illustrative.",
    },
    documents: [
      { id: "garden-court-brochure", title: "Project brochure", kind: "brochure", href: null, gated: false },
      { id: "garden-court-site-plan", title: "Site plan", kind: "site-plan", href: null, gated: false },
      { id: "garden-court-price-list", title: "Plot price list", kind: "price-list", href: null, gated: true },
      { id: "garden-court-legal", title: "Title and legal pack", kind: "legal", href: null, gated: true },
      { id: "garden-court-rera", title: "RERA details", kind: "rera", href: null, gated: false },
    ],
    faqs: [
      {
        question: "What plot sizes are available?",
        answer: "Plots run from 360 to 515 square yards. Availability against a specific size is confirmed from the developer's live inventory sheet.",
      },
      {
        question: "Is the layout shown on this page the final one?",
        answer:
          "No. The plan on this page is indicative and exists to show how plot selection will work. Final plot numbers, dimensions and availability come from the released site plan.",
      },
      {
        question: "Can I build immediately after purchase?",
        answer:
          "That depends on the development stage and local approvals. Your advisor will confirm the current position in writing before you commit.",
      },
    ],
    pendingInformation: [
      "Plot-wise pricing",
      "Development and infrastructure status",
      "Connectivity timings",
      "Amenity schedule",
      "Legal and title documentation",
      "RERA registration details",
    ],
    developer: null,
    reraNumber: null,
    possession: null,
    hero: {
      src: "/media/projects/garden-court/hero.svg",
      alt: "Placeholder artwork for Garden Court",
      placeholder: true,
      caption: null,
    },
    gallery: gallery("garden-court", [
      "Placeholder artwork for Garden Court, image 1 of 4",
      "Placeholder artwork for Garden Court, image 2 of 4",
      "Placeholder artwork for Garden Court, image 3 of 4",
      "Placeholder artwork for Garden Court, image 4 of 4",
    ]),
    verified: { project: false, developer: false, location: false, documentation: false, pricing: false, inventory: false },
    lastUpdated: "2026-09-20",
    featured: true,
    editorialRank: 84,
  },
  {
    slug: "we-communities",
    name: "WE Communities",
    positioning: "Live closer to nature. Live for the future.",
    summary: "Sustainable villas in Bangalore and Gurgaon.",
    categories: ["sustainable-living"],
    primaryCategory: "sustainable-living",
    propertyTypes: ["sustainable-villa"],
    intents: ["live-differently", "buy-a-home", "second-home"],
    purposes: ["self-use", "second-home"],
    location: {
      label: "Bangalore & Gurgaon",
      cities: ["Bangalore", "Gurgaon"],
      region: "NCR & Karnataka",
      state: null,
      coordinates: null,
    },
    priceFrom: null,
    priceNote: null,
    area: null,
    bedrooms: [],
    availability: "available",
    specialTags: ["sustainable"],
    usps: [
      "Sustainable villas",
      "Green architecture",
      "Community living",
      "Energy efficiency",
      "Water management",
      "Open spaces and wellness",
    ],
    overview: [
      "WE Communities builds sustainable villa communities in Bangalore and Gurgaon.",
      "The design brief starts from the land: green architecture, water management, energy efficiency and shared open space, rather than sustainability bolted onto a conventional layout.",
    ],
    whyThisProject: [
      "Sustainability is in the plan, not in the brochure.",
      "Present in two metros — Bangalore and Gurgaon — with configurations confirmed per location.",
      "Built around shared space and wellness rather than plot maximisation.",
    ],
    highlights: [
      { label: "Property Type", value: "Sustainable villas", icon: "type" },
      { label: "Location", value: "Bangalore & Gurgaon", icon: "location" },
      { label: "Availability", value: "Available", icon: "status" },
      { label: "Price", value: "On request", icon: "price" },
    ],
    amenities: [],
    connectivity: [],
    intelligence: null,
    commercial: null,
    inventory: [],
    masterplan: null,
    documents: [
      { id: "we-communities-brochure", title: "Community brochure", kind: "brochure", href: null, gated: false },
      { id: "we-communities-site-plan", title: "Site plan", kind: "site-plan", href: null, gated: false },
      { id: "we-communities-specification", title: "Sustainability specification", kind: "specification", href: null, gated: true },
      { id: "we-communities-rera", title: "RERA details", kind: "rera", href: null, gated: false },
    ],
    faqs: [
      {
        question: "What makes these villas sustainable?",
        answer:
          "The brief covers green architecture, energy efficiency, water management and open space. The project-specific specification is shared on request so you can assess it yourself rather than take the label at face value.",
      },
      {
        question: "Are Bangalore and Gurgaon the same product?",
        answer:
          "WE Communities is listed in both cities. Configurations, specifications and pricing are confirmed per location.",
      },
    ],
    pendingInformation: [
      "Villa configurations and built-up areas",
      "Starting price per city",
      "Sustainability certifications",
      "Possession timeline",
      "RERA registration details",
    ],
    developer: null,
    reraNumber: null,
    possession: null,
    hero: {
      src: "/media/projects/we-communities/hero.svg",
      alt: "Placeholder artwork for WE Communities",
      placeholder: true,
      caption: null,
    },
    gallery: gallery("we-communities", [
      "Placeholder artwork for WE Communities, image 1 of 4",
      "Placeholder artwork for WE Communities, image 2 of 4",
      "Placeholder artwork for WE Communities, image 3 of 4",
      "Placeholder artwork for WE Communities, image 4 of 4",
    ]),
    verified: { project: false, developer: false, location: false, documentation: false, pricing: false, inventory: false },
    lastUpdated: "2026-09-20",
    featured: true,
    editorialRank: 80,
  },
  {
    slug: "eth-infra-haridwar-one",
    name: "ETH Infra — Haridwar One",
    positioning: "A new address in Haridwar.",
    summary: "An apartment project in Haridwar by ETH Infra.",
    categories: ["apartments"],
    primaryCategory: "apartments",
    propertyTypes: ["apartment"],
    intents: ["buy-a-home", "second-home"],
    purposes: ["self-use", "investment", "second-home"],
    location: {
      label: "Haridwar, Uttarakhand",
      cities: ["Haridwar"],
      region: "Uttarakhand",
      state: "Uttarakhand",
      coordinates: null,
    },
    priceFrom: null,
    priceNote: null,
    area: null,
    bedrooms: [],
    availability: "available",
    specialTags: [],
    usps: ["Apartments in Haridwar", "Developed by ETH Infra"],
    overview: [
      "Haridwar One is ETH Infra's apartment project in Haridwar.",
      "Haridwar is a year-round destination, and the project is presented for self-use, a second home, or investment.",
    ],
    whyThisProject: [
            "A named developer, whose background is shared as part of the information pack.",
      "Works as a family base, a second home, or a let.",
    ],
    highlights: [
      { label: "Property Type", value: "Apartments", icon: "type" },
      { label: "Location", value: "Haridwar", icon: "location" },
      { label: "Developer", value: "ETH Infra", icon: "status" },
      { label: "Price", value: "On request", icon: "price" },
    ],
    amenities: [],
    connectivity: [],
    intelligence: null,
    commercial: null,
    inventory: [],
    masterplan: null,
    documents: [
      { id: "haridwar-one-brochure", title: "Project brochure", kind: "brochure", href: null, gated: false },
      { id: "haridwar-one-floor-plans", title: "Floor plans", kind: "floor-plan", href: null, gated: true },
      { id: "haridwar-one-price-list", title: "Price list", kind: "price-list", href: null, gated: true },
      { id: "haridwar-one-payment-plan", title: "Payment plan", kind: "payment-plan", href: null, gated: true },
      { id: "haridwar-one-rera", title: "RERA details", kind: "rera", href: null, gated: false },
    ],
    faqs: [
      {
        question: "What configurations are available?",
        answer:
          "Configurations and unit sizes are confirmed from the developer's released inventory. Request details and your advisor will send the current sheet.",
      },
      {
        question: "Who is the developer?",
        answer: "ETH Infra. Developer background and construction status are shared as part of the information pack.",
      },
    ],
    pendingInformation: [
      "Apartment configurations and unit sizes",
      "Starting price",
      "Amenity schedule",
      "Connectivity timings",
      "Construction status and possession",
      "RERA registration details",
    ],
    developer: { name: "ETH Infra", about: null, established: null },
    reraNumber: null,
    possession: null,
    hero: {
      src: "/media/projects/eth-infra-haridwar-one/hero.svg",
      alt: "Placeholder artwork for ETH Infra — Haridwar One",
      placeholder: true,
      caption: null,
    },
    gallery: gallery("eth-infra-haridwar-one", [
      "Placeholder artwork for ETH Infra — Haridwar One, image 1 of 4",
      "Placeholder artwork for ETH Infra — Haridwar One, image 2 of 4",
      "Placeholder artwork for ETH Infra — Haridwar One, image 3 of 4",
      "Placeholder artwork for ETH Infra — Haridwar One, image 4 of 4",
    ]),
    verified: { project: false, developer: false, location: false, documentation: false, pricing: false, inventory: false },
    lastUpdated: "2026-09-20",
    featured: false,
    editorialRank: 76,
  },
  {
    slug: "verdaant-court",
    name: "Verdaant Court",
    positioning: "A premium address. A long-term asset.",
    summary: "Residential plots on the Goa–Maharashtra border.",
    categories: ["plots"],
    primaryCategory: "plots",
    propertyTypes: ["plot"],
    intents: ["own-land", "second-home"],
    purposes: ["land-banking", "capital-appreciation", "investment"],
    location: {
      label: "Goa–Maharashtra Border",
      cities: ["Goa", "Maharashtra"],
      region: "Goa–Maharashtra border",
      state: null,
      coordinates: null,
    },
    priceFrom: null,
    priceNote: null,
    area: null,
    bedrooms: [],
    availability: "available",
    specialTags: ["premium-location"],
    usps: ["Residential plots", "Goa–Maharashtra border location"],
    overview: [
      "Verdaant Court is a plotted residential development on the Goa–Maharashtra border.",
      "It is positioned as an address first and a holding second — land bought for where it sits rather than for a quick turn.",
    ],
    whyThisProject: [
      "An address-led plot purchase rather than a purely numerical one.",
      "The same border corridor that serves the wider Goa second-home market.",
      "A long-horizon holding; whether a build timeline applies is confirmed from the development's terms.",
    ],
    highlights: [
      { label: "Property Type", value: "Residential plots", icon: "type" },
      { label: "Location", value: "Goa–Maharashtra border", icon: "location" },
      { label: "Availability", value: "Available", icon: "status" },
      { label: "Price", value: "On request", icon: "price" },
    ],
    amenities: [],
    connectivity: [],
    intelligence: null,
    commercial: null,
    inventory: [],
    masterplan: null,
    documents: [
      { id: "verdaant-court-brochure", title: "Project brochure", kind: "brochure", href: null, gated: false },
      { id: "verdaant-court-site-plan", title: "Site plan", kind: "site-plan", href: null, gated: false },
      { id: "verdaant-court-price-list", title: "Plot price list", kind: "price-list", href: null, gated: true },
      { id: "verdaant-court-legal", title: "Title and legal pack", kind: "legal", href: null, gated: true },
    ],
    faqs: [
      {
        question: "How does Verdaant Court differ from Garden Court?",
        answer:
          "Both are plotted developments in the same border corridor. Positioning differs, and so do layout and pricing. Compare them side by side, then ask an advisor for the current inventory on each.",
      },
      {
        question: "What plot sizes are offered?",
        answer: "Plot dimensions are confirmed from the released site plan. Request details and your advisor will share the current schedule.",
      },
    ],
    pendingInformation: [
      "Plot sizes and dimensions",
      "Plot-wise pricing",
      "Infrastructure and development details",
      "Connectivity timings",
      "Investment rationale pack",
      "Legal and title documentation",
    ],
    developer: null,
    reraNumber: null,
    possession: null,
    hero: {
      src: "/media/projects/verdaant-court/hero.svg",
      alt: "Placeholder artwork for Verdaant Court",
      placeholder: true,
      caption: null,
    },
    gallery: gallery("verdaant-court", [
      "Placeholder artwork for Verdaant Court, image 1 of 4",
      "Placeholder artwork for Verdaant Court, image 2 of 4",
      "Placeholder artwork for Verdaant Court, image 3 of 4",
      "Placeholder artwork for Verdaant Court, image 4 of 4",
    ]),
    verified: { project: false, developer: false, location: false, documentation: false, pricing: false, inventory: false },
    lastUpdated: "2026-09-20",
    featured: false,
    editorialRank: 70,
  },
  {
    slug: "yugen",
    name: "Yugen",
    positioning: "Land today. Possibility tomorrow.",
    summary: "Plots and villas on the Goa–Maharashtra border.",
    categories: ["plots", "villas"],
    primaryCategory: "plots",
    propertyTypes: ["plot", "villa"],
    intents: ["own-land", "second-home"],
    purposes: ["land-banking", "capital-appreciation", "second-home"],
    location: {
      label: "Goa–Maharashtra Border",
      cities: ["Goa", "Maharashtra"],
      region: "Goa–Maharashtra border",
      state: null,
      coordinates: null,
    },
    priceFrom: null,
    priceNote: null,
    area: null,
    bedrooms: [],
    availability: "available",
    specialTags: [],
    usps: ["Plots and villas", "Goa–Maharashtra border location"],
    overview: [
      "Yugen offers both plots and villas on the Goa–Maharashtra border.",
      "The choice is the point: take land and build later, or take a villa and skip the wait.",
    ],
    whyThisProject: [
      "Two entry points in one development — land or a finished villa.",
      "A holding that can convert into a second home when you are ready.",
      "The same corridor as Garden Court and Verdaant Court, so the three compare cleanly.",
    ],
    highlights: [
      { label: "Property Type", value: "Plots & villas", icon: "type" },
      { label: "Location", value: "Goa–Maharashtra border", icon: "location" },
      { label: "Availability", value: "Available", icon: "status" },
      { label: "Price", value: "On request", icon: "price" },
    ],
    amenities: [],
    connectivity: [],
    intelligence: null,
    commercial: null,
    inventory: [],
    masterplan: null,
    documents: [
      { id: "yugen-brochure", title: "Project brochure", kind: "brochure", href: null, gated: false },
      { id: "yugen-site-plan", title: "Site plan", kind: "site-plan", href: null, gated: false },
      { id: "yugen-price-list", title: "Price list", kind: "price-list", href: null, gated: true },
      { id: "yugen-legal", title: "Title and legal pack", kind: "legal", href: null, gated: true },
    ],
    faqs: [
      {
        question: "Can I buy a plot now and a villa later?",
        answer:
          "Yugen offers both formats. Whether a specific plot can convert to a built villa depends on the development's terms, which your advisor will confirm in writing.",
      },
      {
        question: "What are the plot dimensions?",
        answer: "Dimensions come from the released site plan. Request details and your advisor will share the current schedule.",
      },
    ],
    pendingInformation: [
      "Plot dimensions and villa configurations",
      "Pricing for both formats",
      "Infrastructure and development status",
      "Connectivity timings",
      "Availability schedule",
    ],
    developer: null,
    reraNumber: null,
    possession: null,
    hero: {
      src: "/media/projects/yugen/hero.svg",
      alt: "Placeholder artwork for Yugen",
      placeholder: true,
      caption: null,
    },
    gallery: gallery("yugen", [
      "Placeholder artwork for Yugen, image 1 of 4",
      "Placeholder artwork for Yugen, image 2 of 4",
      "Placeholder artwork for Yugen, image 3 of 4",
      "Placeholder artwork for Yugen, image 4 of 4",
    ]),
    verified: { project: false, developer: false, location: false, documentation: false, pricing: false, inventory: false },
    lastUpdated: "2026-09-20",
    featured: false,
    editorialRank: 66,
  },
];

export const projectBySlug = new Map(projects.map((p) => [p.slug, p]));
